### ISSUE TITLE
Fresh install fails due to missing _assets folder

### ISSUE THREAD

**Issue by jeppevinkel** [BOLL7708/desbot#15]
After a fresh install, the php fails to run due to a missing `_assets` folder.

The error output is as follows
```bash
[Sun Jan 14 00:19:00.294778 2024] [php:error] [pid 24400:tid 1896] [client 127.0.0.1:64209] PHP Fatal error:  Uncaught UnexpectedValueException: FilesystemIterator::__construct(_assets): The system cannot find the file specifi (code: 2) in C:\\xampp\\htdocs\\desbot\\_assets.php:7\nStack trace:\n#0 C:\\xampp\\htdocs\\desbot\\_assets.php(7): FilesystemIterator->__construct('_assets', 12288)\n#1 C:\\xampp\\htdocs\\desbot\\_assets.php(18): listFolderFiles('_assets', Array)\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\desbot\\_assets.php on line 7, referer: http://localhost/desbot/widget.php
[Sun Jan 14 00:19:32.621655 2024] [php:error] [pid 24400:tid 1888] [client 127.0.0.1:64280] PHP Fatal error:  Uncaught UnexpectedValueException: FilesystemIterator::__construct(_assets): The system cannot find the file specifi (code: 2) in C:\\xampp\\htdocs\\desbot\\_assets.php:7\nStack trace:\n#0 C:\\xampp\\htdocs\\desbot\\_assets.php(7): FilesystemIterator->__construct('_assets', 12288)\n#1 C:\\xampp\\htdocs\\desbot\\_assets.php(18): listFolderFiles('_assets', Array)\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\desbot\\_assets.php on line 7, referer: http://localhost/desbot/widget.php
[Sun Jan 14 00:20:49.104108 2024] [php:error] [pid 24400:tid 1856] [client 127.0.0.1:64347] PHP Fatal error:  Uncaught UnexpectedValueException: FilesystemIterator::__construct(_assets): The system cannot find the file specifi (code: 2) in C:\\xampp\\htdocs\\desbot\\_assets.php:7\nStack trace:\n#0 C:\\xampp\\htdocs\\desbot\\_assets.php(7): FilesystemIterator->__construct('_assets', 12288)\n#1 C:\\xampp\\htdocs\\desbot\\_assets.php(18): listFolderFiles('_assets', Array)\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\desbot\\_assets.php on line 7, referer: http://localhost/desbot/widget.php
[Sun Jan 14 00:20:50.699610 2024] [php:error] [pid 24400:tid 1896] [client 127.0.0.1:64343] PHP Fatal error:  Uncaught UnexpectedValueException: FilesystemIterator::__construct(_assets): The system cannot find the file specifi (code: 2) in C:\\xampp\\htdocs\\desbot\\_assets.php:7\nStack trace:\n#0 C:\\xampp\\htdocs\\desbot\\_assets.php(7): FilesystemIterator->__construct('_assets', 12288)\n#1 C:\\xampp\\htdocs\\desbot\\_assets.php(18): listFolderFiles('_assets', Array)\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\desbot\\_assets.php on line 7, referer: http://localhost/desbot/widget.php
[Sun Jan 14 00:20:59.467504 2024] [php:error] [pid 24400:tid 1856] [client ::1:64368] PHP Fatal error:  Uncaught UnexpectedValueException: FilesystemIterator::__construct(_assets): The system cannot find the file specifi (code: 2) in C:\\xampp\\htdocs\\desbot\\_assets.php:7\nStack trace:\n#0 C:\\xampp\\htdocs\\desbot\\_assets.php(7): FilesystemIterator->__construct('_assets', 12288)\n#1 C:\\xampp\\htdocs\\desbot\\_assets.php(18): listFolderFiles('_assets', Array)\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\desbot\\_assets.php on line 7, referer: http://localhost/desbot/widget.php
[Sun Jan 14 00:21:07.437989 2024] [php:error] [pid 24400:tid 1876] [client ::1:64411] PHP Fatal error:  Uncaught UnexpectedValueException: FilesystemIterator::__construct(_assets): The system cannot find the file specifi (code: 2) in C:\\xampp\\htdocs\\desbot\\_assets.php:7\nStack trace:\n#0 C:\\xampp\\htdocs\\desbot\\_assets.php(7): FilesystemIterator->__construct('_assets', 12288)\n#1 C:\\xampp\\htdocs\\desbot\\_assets.php(18): listFolderFiles('_assets', Array)\n#2 {main}\n  thrown in C:\\xampp\\htdocs\\desbot\\_assets.php on line 7, referer: http://localhost/desbot/widget.php
```

**Comment by BOLL7708** [comment]
Should be fixed in v7.6.1, soon.
